export default {
    CHANGE_MESSAGES_TYPE: 'CHANGE_MESSAGES_TYPE',
    CHANGE_ALL_MESSAGES_TYPE: 'CHANGE_ALL_MESSAGES_TYPE',
    START_CHANGE_MESSADE_LOADING: 'START_CHANGE_MESSADE_LOADING',
    FINISH_CHANGE_MESSADE_LOADING: 'FINISH_CHANGE_MESSADE_LOADING',
    RECIVERD_MESSAGES: 'RECIVERD_MESSAGES',
    RECIVERD_MORE_MESSAGES: 'RECIVERD_MORE_MESSAGES',
}